# Backend build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o inner-gateway ./cmd/inner

# Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/inner-gateway .

EXPOSE 9901

ENTRYPOINT ["./inner-gateway"]
CMD ["-l", "0.0.0.0:9901"]
